### ISSUE TITLE
Trying to implement GetNodeCpuStats

### ISSUE THREAD

**Issue by tugba2** [rgbkrk/libvirt-go#75]
I am trying to implement CPU and RAM stats for host. Looking at ListAllStoragePools, I implemented the following but it crashes:

```go
func (c *VirConnection) GetNodeCPUStats(flags C.uint) (VirNodeCPUStats, error) {
	//var cList *C.virNodeCPUStatsPtr
	var nparams C.int
	var params *C.virNodeCPUStatsPtr
	var cpuNum C.int = -1 //TODO: change with cVIR_NODE_CPU_STATS_ALL_CPUS
	var stats []VirNodeCPUStats

	if C.virNodeGetCPUStats(c.ptr, cpuNum, nil, &nparams, 0) == 0 {
		fmt.Println("D> Successful: virNodeGetCPUStats\nD> nparams: ", nparams)
		retcode := C.virNodeGetCPUStats(c.ptr, cpuNum, (*C.virNodeCPUStats)(unsafe.Pointer(&params)), &nparams, C.uint(0))
		fmt.Println("D> ret code: ", retcode)
	} else {
		//TODO: error handle
		fmt.Println("D> Error occured: virNodeGetCPUStats!")
	}

	fmt.Println("D> params: ", params)

	header := reflect.SliceHeader{
		Data: uintptr(unsafe.Pointer(params)),
		Len:  4,
		Cap:  4,
	}
	slice := *(*[]C.virNodeCPUStatsPtr)(unsafe.Pointer(&header))
	fmt.Println("D> slice: ")
	for _, ptr := range slice {
		stats = append(stats, VirNodeCPUStats{ptr}) //add for first
		fmt.Println("D> stats[0]: ", stats[0])
	}

	C.free(unsafe.Pointer(params))
	return stats[0], nil
}
```

When I try to run the tests (I modified the test so for my test case only, it uses qemu:///system, test:/// does not have cpu stats implemented) it crashes with the following error:

```
D> Successful: virNodeGetCPUStats
D> nparams:  4
D> ret code:  0
D> params:  0x6c656e72656b
D> slice: 
unexpected fault address 0x6c656e72656b
fatal error: fault
[signal 0xb code=0x1 addr=0x6c656e72656b pc=0x4c0aab]

goroutine 87 [running]:
runtime.throw(0x6130d0, 0x5)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820053c38 sp=0xc820053c20
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc820053c88 sp=0xc820053c38
github.com/rgbkrk/libvirt-go.(*VirConnection).GetNodeCPUStats(0xc820053e70, 0x0, 0x0, 0x0, 0x0)
	/home/tugba/go/src/github.com/rgbkrk/libvirt-go/libvirt.go:829 +0x79b fp=0xc820053e30 sp=0xc820053c88
github.com/rgbkrk/libvirt-go.TestGetCPUStats(0xc8200c0ea0)
	/home/tugba/go/src/github.com/rgbkrk/libvirt-go/libvirt_test.go:833 +0x71 fp=0xc820053f58 sp=0xc820053e30
testing.tRunner(0xc8200c0ea0, 0x91acd8)
	/usr/local/go/src/testing/testing.go:473 +0x98 fp=0xc820053f90 sp=0xc820053f58
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd
D> Successful: virNodeGetCPUStats
D> nparams:  4
D> ret code:  0
D> params:  0x6c656e72656b
D> slice: 
unexpected fault address 0x6c656e72656b
fatal error: fault
[signal 0xb code=0x1 addr=0x6c656e72656b pc=0x4c0aab]

goroutine 87 [running]:
runtime.throw(0x6130d0, 0x5)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820053c38 sp=0xc820053c20
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ab fp=0xc820053c88 sp=0xc820053c38
github.com/rgbkrk/libvirt-go.(*VirConnection).GetNodeCPUStats(0xc820053e70, 0x0, 0x0, 0x0, 0x0)
	/home/tugba/go/src/github.com/rgbkrk/libvirt-go/libvirt.go:829 +0x79b fp=0xc820053e30 sp=0xc820053c88
github.com/rgbkrk/libvirt-go.TestGetCPUStats(0xc8200c0ea0)
	/home/tugba/go/src/github.com/rgbkrk/libvirt-go/libvirt_test.go:833 +0x71 fp=0xc820053f58 sp=0xc820053e30
testing.tRunner(0xc8200c0ea0, 0x91acd8)
	/usr/local/go/src/testing/testing.go:473 +0x98 fp=0xc820053f90 sp=0xc820053f58
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820053f98 sp=0xc820053f90
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 1 [chan receive]:
testing.RunTests(0x669e08, 0x91a540, 0x6e, 0x6e, 0x1)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820051ef8, 0xc820000180)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/rgbkrk/libvirt-go/_test/_testmain.go:272 +0x117

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
exit status 2
FAIL	github.com/rgbkrk/libvirt-go	2.067s64.s:1998 +0x1 fp=0xc820053f98 sp=0xc820053f90
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 1 [chan receive]:
testing.RunTests(0x669e08, 0x91a540, 0x6e, 0x6e, 0x1)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820051ef8, 0xc820000180)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/rgbkrk/libvirt-go/_test/_testmain.go:272 +0x117

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
exit status 2
FAIL	github.com/rgbkrk/libvirt-go	2.067s
```

CPUStats is a struct of key value pairs (usually at length 4 in Linux-KVM)

```c
struct virNodeCPUStats {
  char field[VIR_NODE_CPU_STATS_FIELD_LENGTH]	field
  unsigned long long	value
}
```

**Comment by hinesmr** [comment]
@tugba2 You can direct the test to work on specific QEMU targets, to avoid `test:/// ` if you need to by using the QEMU-only version of the libvirt connection, like this:

https://github.com/rgbkrk/libvirt-go/blob/master/libvirt_test.go#L9

We would be happy to get your patch in.
